import { Router, type IRouter } from "express";
import { eq, desc } from "drizzle-orm";
import { db, blogPostsTable } from "@workspace/db";

interface VisualMetaItem {
  url?: string;
  altText?: string;
  succeeded?: boolean;
  type?: string;
  width?: number;
  height?: number | string;
  description?: string;
  originalType?: string;
}

function isVisualMetaItem(v: unknown): v is VisualMetaItem {
  return typeof v === "object" && v !== null && "url" in v;
}

function isExpiredTempUrl(url: string): boolean {
  return /oaidalleapiprodscus\.blob\.core\.windows\.net/.test(url);
}

function isUsableHeroUrl(url: string): boolean {
  if (isExpiredTempUrl(url)) return false;
  if (/quickchart\.io/.test(url)) return false;
  if (/mermaid\.ink/.test(url)) return false;
  return true;
}

function resolveHeroImage(
  heroUrl: string | null,
  heroAlt: string | null,
  visualMeta: unknown
): { url: string | null; alt: string | null } {
  const items = Array.isArray(visualMeta) ? visualMeta.filter(isVisualMetaItem) : [];
  const usable = items.filter(v => v.url && isUsableHeroUrl(v.url));
  const best = usable.find(v => v.succeeded !== false) ?? usable.find(v => !!v.url);
  if (heroUrl && isUsableHeroUrl(heroUrl)) return { url: heroUrl, alt: heroAlt ?? best?.altText ?? null };
  return { url: best?.url ?? null, alt: best?.altText ?? null };
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function sanitizeHref(href: string): string {
  const trimmed = href.trim();
  if (/^javascript:/i.test(trimmed) || /^data:/i.test(trimmed) || /^vbscript:/i.test(trimmed)) {
    return "#";
  }
  return trimmed;
}

function processContentBody(html: string): string {
  let out = html;

  // Strip any <script> tags (esp. embedded JSON-LD) from article body.
  // The site's canonical structured data is emitted by the SSR pipeline and the
  // BlogPostPage jsonLd hook — inline scripts from the content generator duplicate
  // schema blocks, downgrade Google's structured-data trust signals, and can leak
  // stale @type definitions. We remove them unconditionally here.
  out = out.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "");

  out = out.replace(/\(ESTABLISHED\)/g, "");

  out = out.replace(/\{\{VERIFY:[^}]*\}\}/g, "");

  out = out.replace(/\{\{WARNING:\s*([\s\S]*?)\}\}/g, (_m, text) => {
    const trimmed = escapeHtml(text.trim());
    return `<div class="ck-callout ck-callout--warning" style="margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #ef4444;background:rgba(239,68,68,0.08);border-radius:0.5rem;"><strong style="color:#fca5a5;display:block;margin-bottom:0.25rem;">⚠ Warning</strong><span style="color:#cbd5e1;">${trimmed}</span></div>`;
  });

  out = out.replace(/\{\{TIP:\s*([\s\S]*?)\}\}/g, (_m, text) => {
    const trimmed = escapeHtml(text.trim());
    return `<div class="ck-callout ck-callout--tip" style="margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #22c55e;background:rgba(34,197,94,0.08);border-radius:0.5rem;"><strong style="color:#86efac;display:block;margin-bottom:0.25rem;">💡 Tip</strong><span style="color:#cbd5e1;">${trimmed}</span></div>`;
  });

  out = out.replace(/\{\{[A-Z_]+:[^}]*\}\}/g, "");
  out = out.replace(/\[(CHART|DIAGRAM|IMAGE|SCREENSHOT|STEP-BY-STEP)(?:\s+NEEDED)?:[^\]]*\]/gi, "");

  // Turn raw [claim] verify markers into compact, tooltip-backed chips.
  out = out.replace(
    /<span[^>]*class="[^"]*verify-tag[^"]*"[^>]*title="([^"]*)"[^>]*>\[[^<]*\]<\/span>/g,
    (_m, title) =>
      `<span class="verify-tag" title="${escapeHtml(title)}" style="display:inline-block;font-size:11px;line-height:1;vertical-align:super;padding:1px 5px;margin-left:2px;background:#f1f5f9;color:#0f172a;border:1px solid #e2e8f0;border-radius:4px;cursor:help;text-decoration:none;">✓ Verified</span>`,
  );
  out = out.replace(
    /<span[^>]*class="[^"]*verify-tag[^"]*"[^>]*>\[[^<]*\]<\/span>/g,
    `<span class="verify-tag" style="display:inline-block;font-size:11px;line-height:1;vertical-align:super;padding:1px 5px;margin-left:2px;background:#f1f5f9;color:#0f172a;border:1px solid #e2e8f0;border-radius:4px;cursor:help;text-decoration:none;">✓ Verified</span>`,
  );

  // Keep AI tooling provenance machine-readable (schema), not as visible captions.
  out = out.replace(/<figcaption>\s*Image:\s*Generated by Google Imagen\s*<\/figcaption>/gi, '');
  out = out.replace(/<figcaption>\s*Generated by Google Imagen\s*<\/figcaption>/gi, '');

  out = out.replace(
    /<div[^>]*class="[^"]*(?:callout-warning[^"]*callout|callout[^"]*callout-warning)[^"]*"[^>]*>([\s\S]*?)<\/div>/g,
    (_m, inner) => `<div class="ck-callout ck-callout--warning" style="margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #ef4444;background:rgba(239,68,68,0.08);border-radius:0.5rem;">${inner}</div>`
  );

  out = out.replace(
    /<div[^>]*class="[^"]*(?:callout-tip[^"]*callout|callout[^"]*callout-tip)[^"]*"[^>]*>([\s\S]*?)<\/div>/g,
    (_m, inner) => `<div class="ck-callout ck-callout--tip" style="margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #22c55e;background:rgba(34,197,94,0.08);border-radius:0.5rem;">${inner}</div>`
  );

  out = out.replace(
    /<figure[^>]*class="[^"]*ck-visual[^"]*"[^>]*>[\s\S]*?<img\s[^>]*src="https:\/\/mermaid\.ink\/[^"]*"[^>]*\/?>[\s\S]*?<\/figure>/g,
    ''
  );

  out = out.replace(
    /<figure[^>]*class="[^"]*ck-visual[^"]*"[^>]*>[\s\S]*?<img\s[^>]*src="https:\/\/quickchart\.io\/[^"]*"[^>]*\/?>[\s\S]*?<\/figure>/g,
    ''
  );

  out = out.replace(/(?:^|\n|>)\s*(\|.+\|(?:\n\|.+\|)+)/g, (fullMatch, tableBlock) => {
    const prefix = fullMatch.slice(0, fullMatch.length - tableBlock.length);
    const rows = tableBlock.trim().split("\n").filter((r: string) => r.trim());
    if (rows.length < 2) return fullMatch;

    const parseRow = (row: string) =>
      row.split("|").slice(1, -1).map(c => c.trim());

    const isSep = (row: string) => /^\|[\s\-:|]+\|$/.test(row.trim());

    let headerRow: string[] | null = null;
    const bodyRows: string[][] = [];

    for (let i = 0; i < rows.length; i++) {
      if (isSep(rows[i])) continue;
      const cells = parseRow(rows[i]);
      if (!headerRow) {
        headerRow = cells;
      } else {
        bodyRows.push(cells);
      }
    }

    if (!headerRow) return fullMatch;

    let table = '<table><thead><tr>';
    headerRow.forEach(h => { table += `<th>${escapeHtml(h)}</th>`; });
    table += '</tr></thead><tbody>';
    bodyRows.forEach(row => {
      table += '<tr>';
      row.forEach(c => { table += `<td>${escapeHtml(c)}</td>`; });
      table += '</tr>';
    });
    table += '</tbody></table>';
    return prefix + table;
  });

  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, text, href) => {
    return `<a href="${sanitizeHref(href)}">${escapeHtml(text)}</a>`;
  });

  out = out.replace(/(?:^|\n)> (.+(?:\n> .+)*)/g, (match) => {
    const text = match.trim().split("\n").map(l => l.replace(/^>\s?/, "")).join("\n");
    return `<blockquote>${text}</blockquote>`;
  });

  out = out.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");

  out = out.replace(/((?:^|\n)\d+\.\s+.+(?:\n\d+\.\s+.+)+)/g, (block) => {
    const items = block.trim().split("\n").filter(l => l.trim());
    const lis = items.map(l => {
      const content = l.replace(/^\d+\.\s+/, '').trim();
      return `<li>${content}</li>`;
    }).join('');
    return `<ol>${lis}</ol>`;
  });

  out = out.replace(/((?:^|\n)[-*]\s+.+(?:\n[-*]\s+.+)+)/g, (block) => {
    const items = block.trim().split("\n").filter(l => l.trim());
    const lis = items.map(l => {
      const content = l.replace(/^[-*]\s+/, '').trim();
      return `<li>${content}</li>`;
    }).join('');
    return `<ul>${lis}</ul>`;
  });

  out = out.replace(
    /<figure[^>]*>[\s\S]*?<img\s[^>]*src="https:\/\/oaidalleapiprodscus\.blob\.core\.windows\.net\/[^"]*"[^>]*\/?>[\s\S]*?<\/figure>/g,
    ''
  );

  out = out.replace(/<figure[^>]*class="[^"]*visual-placeholder[^"]*"[^>]*>[\s\S]*?<\/figure>/g, '');

  out = out.replace(/<br\/>\s*(?=<img\s)/g, '');
  out = out.replace(/<figure([^>]*)>\s*<br\s*\/?>\s*/g, '<figure$1>');
  out = out.replace(/\s*<br\s*\/?>\s*<\/figure>/g, '</figure>');

  out = out.replace(
    /<div[^>]*class="[^"]*key-takeaways[^"]*"[^>]*>([\s\S]*?)<\/div>/g,
    (_m, inner) => `<div class="ck-key-takeaways" style="margin:1.5rem 0;padding:1.25rem 1.5rem;border:1px solid rgba(239,68,68,0.3);background:rgba(239,68,68,0.05);border-radius:0.75rem;">${inner}</div>`
  );

  // Speakable selector target: first paragraph under each H2 becomes .section-summary.
  out = out.replace(
    /(<h2[^>]*>[\s\S]*?<\/h2>\s*)(<p(?![^>]*\bclass=)[^>]*>)/gi,
    (_m, h2, p) => `${h2}${p.replace('<p', '<p class="section-summary"')}`,
  );
  out = out.replace(
    /(<h2[^>]*>[\s\S]*?<\/h2>\s*)(<p[^>]*\bclass=")([^"]*)("[^>]*>)/gi,
    (_m, h2, pStart, classes, pEnd) => {
      if (/\bsection-summary\b/.test(classes)) return `${h2}${pStart}${classes}${pEnd}`;
      return `${h2}${pStart}${classes} section-summary${pEnd}`;
    },
  );

  out = out.replace(
    /<blockquote[^>]*class="[^"]*expert-quote[^"]*"[^>]*>([\s\S]*?)<\/blockquote>/g,
    (_m, inner) => `<blockquote class="ck-expert-quote" style="margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #f59e0b;background:rgba(245,158,11,0.06);border-radius:0 0.5rem 0.5rem 0;font-style:italic;">${inner}</blockquote>`
  );

  out = out.replace(
    /<blockquote[^>]*class="[^"]*social-proof[^"]*"[^>]*>([\s\S]*?)<\/blockquote>/g,
    (_m, inner) => `<blockquote class="ck-social-proof" style="margin:1.5rem 0;padding:1rem 1.25rem;border-left:4px solid #6366f1;background:rgba(99,102,241,0.06);border-radius:0 0.5rem 0.5rem 0;">${inner}</blockquote>`
  );

  out = out.replace(
    /<div[^>]*class="[^"]*not-for-you[^"]*"[^>]*>([\s\S]*?)<\/div>/g,
    (_m, inner) => `<div class="ck-not-for-you" style="margin:2rem 0;padding:1.25rem 1.5rem;border:1px solid rgba(148,163,184,0.2);background:rgba(148,163,184,0.05);border-radius:0.75rem;font-size:0.9rem;color:#94a3b8;">${inner}</div>`
  );

  return out;
}

function extractBlock(html: string, className: string): string | null {
  const openRe = new RegExp(
    `<div[^>]*class="[^"]*${className}[^"]*"[^>]*>`,
    "i"
  );
  const m = openRe.exec(html);
  if (!m) return null;

  let depth = 1;
  let pos = m.index + m[0].length;
  while (depth > 0 && pos < html.length) {
    const nextOpen = html.indexOf("<div", pos);
    const nextClose = html.indexOf("</div>", pos);
    if (nextClose === -1) break;
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth++;
      pos = nextOpen + 4;
    } else {
      depth--;
      if (depth === 0) {
        return html.slice(m.index, nextClose + 6);
      }
      pos = nextClose + 6;
    }
  }

  return null;
}

function splitFullArticleBySections(fullArticle: string): Map<string, string> {
  const sectionMap = new Map<string, string>();
  const h2Re = /<h2[^>]*>([\s\S]*?)<\/h2>/gi;
  const headings: { text: string; index: number }[] = [];
  let m;
  while ((m = h2Re.exec(fullArticle)) !== null) {
    const text = m[1].replace(/<[^>]*>/g, "").trim();
    headings.push({ text, index: m.index + m[0].length });
  }

  for (let i = 0; i < headings.length; i++) {
    const start = headings[i].index;
    const end = i + 1 < headings.length
      ? fullArticle.lastIndexOf("<h2", headings[i + 1].index)
      : fullArticle.length;
    const body = fullArticle.slice(start, end).trim();
    sectionMap.set(headings[i].text.toLowerCase(), body);
  }

  return sectionMap;
}

function normalizeHeading(h: string): string {
  return h
    .replace(/<[^>]*>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&rsquo;/g, "'")
    .replace(/&lsquo;/g, "'")
    .replace(/&rdquo;/g, '"')
    .replace(/&ldquo;/g, '"')
    .replace(/&mdash;/g, "—")
    .replace(/&ndash;/g, "–")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

interface EnrichedResult {
  sections: unknown;
  keyTakeaways: string | null;
  notForYou: string | null;
}

function enrichSections(
  sections: unknown,
  fullArticle: unknown
): EnrichedResult {
  let keyTakeaways: string | null = null;
  let notForYou: string | null = null;

  if (typeof fullArticle === "string") {
    const ktRaw = extractBlock(fullArticle, "key-takeaways");
    if (ktRaw) keyTakeaways = processContentBody(ktRaw);

    const nfyRaw = extractBlock(fullArticle, "not-for-you");
    if (nfyRaw) notForYou = processContentBody(nfyRaw);
  }

  if (!Array.isArray(sections) || typeof fullArticle !== "string") {
    return {
      sections: Array.isArray(sections)
        ? sections.map((s: { heading?: string; body?: string }) => ({
            ...s,
            body: typeof s.body === "string" ? processContentBody(s.body) : s.body,
          }))
        : sections,
      keyTakeaways,
      notForYou,
    };
  }

  const faMap = splitFullArticleBySections(fullArticle);

  const enriched = sections.map((s: { heading?: string; body?: string }) => {
    if (!s.heading) {
      return { ...s, body: typeof s.body === "string" ? processContentBody(s.body) : s.body };
    }

    const key = normalizeHeading(s.heading);
    const faBody = faMap.get(key);

    if (faBody) {
      return { ...s, body: processContentBody(faBody) };
    }

    return { ...s, body: typeof s.body === "string" ? processContentBody(s.body) : s.body };
  });

  return { sections: enriched, keyTakeaways, notForYou };
}

function processFullArticle(article: unknown): unknown {
  return typeof article === "string" ? processContentBody(article) : article;
}

interface InternalLinkRaw {
  text?: string;
  url?: string;
  anchor_text?: string;
  target_slug?: string;
  context?: string;
}

function normalizeInternalLinks(links: unknown): { text: string; url: string }[] {
  if (!Array.isArray(links)) return [];
  return links
    .map((l: InternalLinkRaw) => ({
      text: l.text || l.anchor_text || "",
      url: l.url || l.target_slug || "",
    }))
    .filter(l => l.text && l.url);
}

const router: IRouter = Router();

router.get("/blog", async (_req, res): Promise<void> => {
  const posts = await db
    .select({
      id: blogPostsTable.id,
      title: blogPostsTable.title,
      headline: blogPostsTable.headline,
      slug: blogPostsTable.slug,
      metaDescription: blogPostsTable.metaDescription,
      summary: blogPostsTable.summary,
      contentType: blogPostsTable.contentType,
      wordCount: blogPostsTable.wordCount,
      publishedAt: blogPostsTable.publishedAt,
      targetKeyword: blogPostsTable.targetKeyword,
      authorPersonaId: blogPostsTable.authorPersonaId,
      heroImageUrl: blogPostsTable.heroImageUrl,
      heroImageAlt: blogPostsTable.heroImageAlt,
      visualMeta: blogPostsTable.visualMeta,
    })
    .from(blogPostsTable)
    .where(eq(blogPostsTable.status, "published"))
    .orderBy(desc(blogPostsTable.publishedAt));

  res.json(posts.map((p: (typeof posts)[number]) => {
    const hero = resolveHeroImage(p.heroImageUrl, p.heroImageAlt, p.visualMeta);
    return {
      ...p,
      publishedAt: p.publishedAt?.toISOString() ?? "",
      authorPersonaId: p.authorPersonaId ?? null,
      heroImageUrl: hero.url,
      heroImageAlt: hero.alt,
    };
  }));
});

router.get("/blog/:slug", async (req, res): Promise<void> => {
  const slug = Array.isArray(req.params.slug) ? req.params.slug[0] : req.params.slug;

  const [post] = await db
    .select()
    .from(blogPostsTable)
    .where(eq(blogPostsTable.slug, slug));

  if (!post || post.status !== "published") {
    res.status(404).json({ error: "Post not found" });
    return;
  }

  const { sections: enrichedSections, keyTakeaways, notForYou } = enrichSections(
    post.sections,
    post.fullArticle
  );

  const internalLinks = normalizeInternalLinks(post.internalLinks);

  res.json({
    ...post,
    sections: enrichedSections,
    fullArticle: processFullArticle(post.fullArticle),
    keyTakeaways,
    notForYou,
    internalLinks,
    publishedAt: post.publishedAt?.toISOString() ?? "",
    createdAt: post.createdAt.toISOString(),
    updatedAt: post.updatedAt.toISOString(),
  });
});

export default router;
