-- ─────────────────────────────────────────────────────────────────────────────
-- Review rich-content columns — add 8 columns to public.reviews
-- ─────────────────────────────────────────────────────────────────────────────
-- Part of Architecture A (Apr 2026): the Vercel /api/sync/review webhook is
-- now the single source of truth for review data on this Replit site, and the
-- old 2-minute Supabase scheduler is being retired. This migration adds the
-- columns the webhook needs to persist the full review content that was
-- previously dropped silently:
--
--   • hero_image_url / hero_image_alt  — top-of-page hero visual generated
--     by the Imagen polish pipeline (lives on Supabase storage)
--   • content_images                   — inline section images
--                                        (array of { url, alt, credit, placement })
--   • visual_meta                      — chart / diagram / infographic metadata
--                                        produced by the polish pipeline; each
--                                        element is { type, url, altText,
--                                        description, succeeded }
--   • protection_steps                 — high-intent "what to do if you were
--                                        scammed by this brand" section
--   • sources                          — typed citation[] (regulatory bodies,
--                                        news coverage, investigative reports)
--   • not_for_you                      — "this review may not apply if..."
--                                        qualifier block, helps with E-E-A-T
--                                        and reduces takedown risk
--   • expertise_depth                  — YMYL author depth-of-knowledge block
--                                        (distinct from methodology_text,
--                                        which describes process)
--
-- Every column is ADD COLUMN IF NOT EXISTS so this migration is idempotent.
-- Drizzle Kit push will also converge to this schema from the TypeScript
-- definitions in lib/db/src/schema/reviews.ts.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS hero_image_url     text,
  ADD COLUMN IF NOT EXISTS hero_image_alt     text,
  ADD COLUMN IF NOT EXISTS content_images     jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS visual_meta        jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS protection_steps   text  NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS sources            jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS not_for_you        text  NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS expertise_depth    text  NOT NULL DEFAULT '';

COMMENT ON COLUMN reviews.hero_image_url   IS 'Top-of-page hero image URL (Supabase storage, generated by Imagen)';
COMMENT ON COLUMN reviews.hero_image_alt   IS 'Alt text for the hero image (accessibility + image SEO)';
COMMENT ON COLUMN reviews.content_images   IS 'Inline section images: array of { url, alt, credit, creditUrl, placement }';
COMMENT ON COLUMN reviews.visual_meta      IS 'Chart/diagram/infographic metadata: array of { type, url, altText, description, succeeded }';
COMMENT ON COLUMN reviews.protection_steps IS 'Victim next-steps section — highest-intent content on the page, drives conversion';
COMMENT ON COLUMN reviews.sources          IS 'Typed citations array: { title, url, type, accessed_date } for regulator/news/research refs';
COMMENT ON COLUMN reviews.not_for_you      IS 'Qualifier callout: when this review may not apply (reduces takedown risk, E-E-A-T signal)';
COMMENT ON COLUMN reviews.expertise_depth  IS 'YMYL author knowledge-depth block, distinct from methodology_text (which describes process)';
