import express, { type Express } from "express";
import cors from "cors";
import pinoHttp from "pino-http";
import router from "./routes";
import { logger } from "./lib/logger";
import { knownAgentsMiddleware } from "./lib/known-agents";

const app: Express = express();

// Trust the first upstream proxy so req.ip reflects the real client address
// from the X-Forwarded-For header set by Replit's reverse proxy, rather than
// the proxy's own IP. This is required for per-IP rate limiting to work.
app.set("trust proxy", 1);

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req) {
        return {
          id: req.id,
          method: req.method,
          url: req.url?.split("?")[0],
        };
      },
      res(res) {
        return {
          statusCode: res.statusCode,
        };
      },
    },
  }),
);
app.use(cors());
// Track every incoming request for AI agent / bot analytics via Known Agents.
// Reads KNOWNAGENTS_ACCESS_TOKEN from env; no-ops if the secret is unset so
// local dev and missing-env deploys continue to work. Mounted before body
// parsers so trackVisit fires for *every* response, including 413s.
app.use(knownAgentsMiddleware);
// Tighter body limit for the public unauthenticated scam-report endpoint.
// Must be mounted BEFORE the global parsers so body-parser enforces 50kb on
// this path and marks req._body = true, causing the global parsers below to
// skip re-parsing the already-consumed body stream.
app.use("/api/reports", express.json({ limit: "50kb" }));
app.use("/api/reports", express.urlencoded({ extended: true, limit: "50kb" }));

// Express's default body limit is 100kb; full review payloads (with long
// articles, red_flags, faq, visual_meta, etc.) and the Vercel admin's
// /sync/blog payload (with schema_enrichment arrays — ClaimReview[],
// HowTo steps, citations[], quotes[]) routinely exceed that and get
// rejected as 413 Payload Too Large before any route handler runs.
// 10mb is a safe ceiling for server-to-server sync traffic while still
// capping truly runaway requests.
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ extended: true, limit: "10mb" }));

// Standard SEO tooling checks /sitemap.xml first. The XML is generated by the
// API router at /api/sitemap.xml; keep a root alias so crawlers/tools don't see
// a 404 before reading robots.txt.
app.get("/sitemap.xml", (_req, res) => {
  res.redirect(301, "/api/sitemap.xml");
});

app.use("/api", router);

export default app;
