import express, { type Express } from "express";
import cors from "cors";
import pinoHttp from "pino-http";
import router from "./routes";
import { logger } from "./lib/logger";

const app: Express = express();

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req) {
        return {
          id: req.id,
          method: req.method,
          url: req.url?.split("?")[0],
        };
      },
      res(res) {
        return {
          statusCode: res.statusCode,
        };
      },
    },
  }),
);
app.use(cors());
// Express's default body limit is 100kb; full review payloads (with long
// articles, red_flags, faq, visual_meta, etc.) and the Vercel admin's
// /sync/blog payload (with schema_enrichment arrays — ClaimReview[],
// HowTo steps, citations[], quotes[]) routinely exceed that and get
// rejected as 413 Payload Too Large before any route handler runs.
// 10mb is a safe ceiling for server-to-server sync traffic while still
// capping truly runaway requests.
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ extended: true, limit: "10mb" }));

// Standard SEO tooling checks /sitemap.xml first. The XML is generated by the
// API router at /api/sitemap.xml; keep a root alias so crawlers/tools don't see
// a 404 before reading robots.txt.
app.get("/sitemap.xml", (_req, res) => {
  res.redirect(301, "/api/sitemap.xml");
});

app.use("/api", router);

export default app;
